theme: minima

title: grzracz
url: "https://grzracz.github.io"
baseurl: "/blog"

author:
  name: grzracz
  email: greg@kymi.games

minima:
  skin: dark

github_username: grzracz
linkedin_username: grzracz

header_pages:
  - about.md

show_excerpts: true
