theme: minima

title: grzracz
url: "https://grzra.cz"
baseurl: "/"

author:
  name: grzracz
  email: greg@kymi.games

minima:
  skin: dark

github_username: grzracz
linkedin_username: grzracz

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
